import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
   return (
      <div className={styles.container}>
         <Head>
            <title>Easybank</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/favicon-32x32.png" />
         </Head>

         <h1>easybank landing page</h1>
      </div>
   )
}

export default Home
