import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
   return (
      <>
         <Head>
            <title>Easybank</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/favicon-32x32.png" />
         </Head>

         <h1>easybank landing page</h1>
      </>
   )
}

export default Home
